//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySanXuat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrintRibbon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintRibbon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLySanXuat.PrintRibbon", typeof(PrintRibbon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.AD.
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁN THÀNH PHẨM.
        /// </summary>
        public static string banthanhpham {
            get {
                return ResourceManager.GetString("banthanhpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Thành Công.
        /// </summary>
        public static string capnhat {
            get {
                return ResourceManager.GetString("capnhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật Thất Bại.
        /// </summary>
        public static string capnhatthatbai {
            get {
                return ResourceManager.GetString("capnhatthatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Ngoại Tệ.
        /// </summary>
        public static string chonngoaite {
            get {
                return ResourceManager.GetString("chonngoaite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTF.
        /// </summary>
        public static string ctf {
            get {
                return ResourceManager.GetString("ctf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTP.
        /// </summary>
        public static string ctp {
            get {
                return ResourceManager.GetString("ctp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string dangnhapthanhcong {
            get {
                return ResourceManager.GetString("dangnhapthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại.
        /// </summary>
        public static string dangnhapthatbai {
            get {
                return ResourceManager.GetString("dangnhapthatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH THIẾP.
        /// </summary>
        public static string danhthiep {
            get {
                return ResourceManager.GetString("danhthiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|Excel Files (.xlsx)|*.xlsx.
        /// </summary>
        public static string dinhdangexcel {
            get {
                return ResourceManager.GetString("dinhdangexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files(*.*)| *.*| Image Files (*.jpg) | *.jpg.
        /// </summary>
        public static string dinhdanghinh {
            get {
                return ResourceManager.GetString("dinhdanghinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPOCH.
        /// </summary>
        public static string EPOCH {
            get {
                return ResourceManager.GetString("EPOCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN CHỮ VI TÍNH.
        /// </summary>
        public static string inchu {
            get {
                return ResourceManager.GetString("inchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KẾ TOÁN.
        /// </summary>
        public static string ketoan {
            get {
                return ResourceManager.GetString("ketoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHOBTP_TP.
        /// </summary>
        public static string khobtp {
            get {
                return ResourceManager.GetString("khobtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHONVL.
        /// </summary>
        public static string khonvl {
            get {
                return ResourceManager.GetString("khonvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIỂM PHẨM.
        /// </summary>
        public static string kiempham {
            get {
                return ResourceManager.GetString("kiempham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KỸ THUẬT SỐ.
        /// </summary>
        public static string kts {
            get {
                return ResourceManager.GetString("kts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATEX.
        /// </summary>
        public static string MATEX {
            get {
                return ResourceManager.GetString("MATEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.NA.
        /// </summary>
        public static string NAVIC {
            get {
                return ResourceManager.GetString("NAVIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGHIỆP VỤ.
        /// </summary>
        public static string nghiepvu {
            get {
                return ResourceManager.GetString("nghiepvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGUYÊN VẬT LIỆU.
        /// </summary>
        public static string nguyenvatlieu {
            get {
                return ResourceManager.GetString("nguyenvatlieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFSET.
        /// </summary>
        public static string offset {
            get {
                return ResourceManager.GetString("offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ CHẤT LƯỢNG.
        /// </summary>
        public static string qlcl {
            get {
                return ResourceManager.GetString("qlcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ SẢN XUẤT.
        /// </summary>
        public static string qlsx {
            get {
                return ResourceManager.GetString("qlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ClosePreview {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ClosePreviewLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Customize {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Customize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_CustomizeLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Document {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_DocumentMap {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_DocumentMapLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_EditPageHF {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_EditPageHFLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportCsv {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportCsvLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportFile {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportFileLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportGraphic {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportGraphicLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportHtm {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportHtmLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportMht {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportMht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportMhtLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportPdf {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportPdfLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportRtf {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportRtfLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportTxt {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportTxtLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportXls {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportXls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportXlsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportXlsx {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ExportXlsxLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsxLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_FillBackground {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_FillBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_FillBackgroundLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Find {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_FindLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_FindLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_HandTool {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_HandTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Magnifier {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_MultiplePages {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_MultiplePagesLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Open {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_OpenLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageMargins {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMargins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsModerate {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsNarrow {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsNormal {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsWide {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageOrientation {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageOrientationLandscape {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageOrientationLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageOrientationPortrait {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PageSetupDialog {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_A3 {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_A4 {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_A5 {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_A6 {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_Executive {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_Legal {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_Letter {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_Tabloid {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperSize {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PaperSizeLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Parameters {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Parameters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ParametersLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Pointer {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Print {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PrintDirect {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PrintDirectLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PrintLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PrintSetup {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_PrintSetupLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Save {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SaveLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Scale {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ScaleLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendCsv {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendCsv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendCsvLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendFile {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendFileLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendGraphic {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendGraphicLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendMht {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendMht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendMhtLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendPdf {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendPdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendPdfLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendRtf {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendRtf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendRtfLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendTxt {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendTxt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendTxtLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendXls {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendXls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendXlsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendXlsx {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendXlsx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_SendXlsxLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendXlsxLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ShowFirstPage {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ShowFirstPageLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ShowLastPage {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ShowLastPageLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ShowNextPage {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ShowNextPageLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ShowPrevPage {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ShowPrevPageLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Thumbnails {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Thumbnails", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ThumbnailsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ThumbnailsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Watermark {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Watermark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_WatermarkLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_Zoom {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ZoomIn {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ZoomInLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ZoomLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ZoomOut {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RibbonPrintPreview_ZoomOutLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAU IN.
        /// </summary>
        public static string sauin {
            get {
                return ResourceManager.GetString("sauin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCD.
        /// </summary>
        public static string SCD {
            get {
                return ResourceManager.GetString("SCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STICKER.
        /// </summary>
        public static string sticker {
            get {
                return ResourceManager.GetString("sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEM VẢI.
        /// </summary>
        public static string temvai {
            get {
                return ResourceManager.GetString("temvai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÀNH PHẨM.
        /// </summary>
        public static string thanhpham {
            get {
                return ResourceManager.GetString("thanhpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Thành Công.
        /// </summary>
        public static string themthanhcong {
            get {
                return ResourceManager.GetString("themthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Không Thành Công.
        /// </summary>
        public static string themthatbai {
            get {
                return ResourceManager.GetString("themthatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIẾT KẾ.
        /// </summary>
        public static string thietke {
            get {
                return ResourceManager.GetString("thietke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math.Round.
        /// </summary>
        public static string Tinh {
            get {
                return ResourceManager.GetString("Tinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.VST.
        /// </summary>
        public static string VEST {
            get {
                return ResourceManager.GetString("VEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XUẤT NHẬP KHẨU.
        /// </summary>
        public static string xnk {
            get {
                return ResourceManager.GetString("xnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Thành Công.
        /// </summary>
        public static string xoathanhcong {
            get {
                return ResourceManager.GetString("xoathanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Thất Bại.
        /// </summary>
        public static string xoathatbai {
            get {
                return ResourceManager.GetString("xoathatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.YOSHIK.
        /// </summary>
        public static string YOSHIKAWA {
            get {
                return ResourceManager.GetString("YOSHIKAWA", resourceCulture);
            }
        }
    }
}
